server.port: 8096

spring:
  jackson.deserialization.fail-on-unknown-properties: false
  groovy.template.check-template-location: false

metrics.path:
  country: pl
  app: loanApplicationService

stubrunner.stubs:
  repository.root: "http://dl.bintray.com/4finance/micro"
  group: com.ofg
  module: stubs

